# Generated by Django 5.2.5 on 2025-10-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_userid_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='watched_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
