# Generated by Django 5.2.5 on 2025-10-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_watched_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
