# Generated by Django 5.2.5 on 2025-09-30 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_userprofile_userid_userprofile_user_and_more'),
        ('features', '0002_videocategory_taggedvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weights', models.FloatField(blank=0, default=0)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_metadata', to='features.videocategory')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='accounts.userprofile')),
            ],
        ),
    ]
