# Generated by Django 5.2.5 on 2025-10-10 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
        ('features', '0002_videocategory_taggedvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermetadata',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='features.videocategory'),
        ),
    ]
